###
GET http://127.0.0.1:8000/


###
GET http://127.0.0.1:8000/flight


###
GET http://127.0.0.1:8000/flight/63b7f935ad906ecf281004f2


###
POST http://127.0.0.1:8000/flight
Content-Type: application/json

{
"Name":"new flight"
}